# Generated by Django 4.1.6 on 2023-02-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="like_users",
            field=models.ManyToManyField(blank=True, to="chat_app.appuser"),
        ),
    ]
